resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:434defaefd21ebbdd137760ea2d52299717d30ab65bd06b0808a39388aa861d0
  name: controller
  newName: quay.io/okd/scos-content
