resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:c0a5824637e970c2053adcba0d568356d6bad675efff719f472661d6fcb495f5
  name: controller
  newName: quay.io/okd/scos-content
