on:
  push:
    branches:
      - "main"
    paths:
      - 'cert-manager/**'
  workflow_dispatch: # Allow manual trigger

name: Deploy Cert-Manager

jobs:
  deploy:
    name: Deploy Cert-Manager
    uses: ./.github/workflows/operator-deploy.yaml
    with:
      operator: cert-manager
    secrets: inherit