on:
  push:
    branches:
      - "main"
    paths:
      - 'external-secrets/**'
  workflow_dispatch: # Allow manual trigger

name: Deploy External-Secrets

jobs:
  deploy:
    name: Deploy External-Secrets
    uses: ./.github/workflows/operator-deploy.yaml
    with:
      operator: external-secrets
    secrets: inherit
