on:
  push:
    branches:
      - "main"
    paths:
      - 'kube-descheduler/**'
  workflow_dispatch: # Allow manual trigger

name: Deploy Kube-Descheduler

jobs:
  deploy:
    name: Deploy Kube-Descheduler
    uses: ./.github/workflows/operator-deploy.yaml
    with:
      operator: kube-descheduler
    secrets: inherit
